
[variables]
    PORT = "3020"
    NODE_ENV = "production"

[phases.setup]
    nixPkgs = ["nodePackages.npm", "nodejs"]

[phases.build]
    dependsOn = ["setup"]
    cmds = ["npm install", "npm run build"]

[start]
    cmd = "npx vite preview --port 3020 --host"
